### ISSUE TITLE
research areas not displaying correctly on frontend staff lists

### ISSUE THREAD

**Issue by maladd** [carcam/jresearch#1]
Research Areas show up as "Uncategorized" on the front end staff lists. Changing line 511 in administrator/components/com_jresearch/tables/member.php...
< return $db->loadColumn();

> return $db->loadObjectList();

fixes the problem on the front, but then the backend staff page breaks. 

Any thoughts?

**Comment by carcam** [comment]
Please check the fix on this commit:

fefc62feb59186c176fa0e04c02b7f071426a8ca

Thank you for the report!!
