### ISSUE TITLE
Staff display limited to 25 in 3.1 stable

### ISSUE THREAD

**Issue by timmiesmith** [carcam/jresearch#12]
Running J!Research 3.1 the display of Staff is limited to 25 people.  There's no pagination shown.  The post at http://joomlacode.org/gf/project/jresearch/forum/?_forum_action=ForumMessageBrowse&thread_id=24709&action=ForumBrowse&forum_id=9972 mentions a "Staff members per page" option, but that appears to have been removed in 3.1.

**Comment by timmiesmith** [comment]
Resolved by adding the field to views/staff/tmpl/positions.xml.  Will send a pull request.

**Comment by lgalarra** [comment]
Hi timmiesmith,

Sorry for the unresponsiveness, I have been extremely busy in the latest weeks. I will start the roadmap towards J!Research 3.2 next week and I will be glad to solve this issue (by integrating your fix). Thank you very much for giving a try to J!Research.

Best,
Luis
