### ISSUE TITLE
link of URL to online version of Publications not showing up

### ISSUE THREAD

**Issue by maladd** [carcam/jresearch#3]
I have set "Online Version" to yes in my menu settings, but online versions of the publications are not showing up. I am ordering by year, but by title and by type are not working correctly either.

**Comment by carcam** [comment]
Hi Maladd, thank you very much for your report. Can you please provide Joomla! and JResearch versions?

**Comment by maladd** [comment]
Joomla 3.4.2 stable and J!Research 3.0 Beta 2

**Comment by carcam** [comment]
Hi Maladd,
this works fine for me. Can you please check that your attachment tag matches the "Online version tag" of your menu item configuration? Otherwise the attachment will not be displayed.

**Comment by maladd** [comment]
Attachment tag? Online version in JResearch 1.22 stable used the URL field to created a link to an external URL. We can't provide files. We provide links to PubMed and when the articles are available for release, it is show there.

**Comment by carcam** [comment]
When adding the URL you can now add a tag to that attachment. This tag needs to match the menu item "Online version tag" if you want it to be displayed on the list.

**Comment by maladd** [comment]
Wait, so the URL field in the 928 publications I just imported is worthless?

**Comment by carcam** [comment]
I need to discuss with Luis about this new feature. I think it's really useful this tag filtering, but I think we also need a way of allowing no filtering at all for showing attachments.

In any case, please bear in mind that this release of JResearch is a beta release not intended for sites in production. Although we appreciate a lot your great help testing the component.

Best!!

**Comment by maladd** [comment]
Understood, but the quicker I can help you find issues, the quicker I hope they will be fixed so I can take my site live. :)

**Comment by lgalarra** [comment]
Hi all, I am back to work in J!Research and have started working towards a new version. I assume that @maladd 's comment regarding the lost URL field is related on how to treat the URL field in Bibtex. The easy solution is to hardcode this mapping and mention it in the tooltip appearing on the field. Working on it now.

**Comment by lgalarra** [comment]
This would also imply to stop using the URL field in the publication forms.

**Comment by lgalarra** [comment]
I have found a better solution. I added an option that allows to associate the URL to either (a) the URL field in the form or (b) an attachment with a particular tag. In this way, @maladd can still keep the URLs stored in the traditional url field. Do you want me to send you a patch for this or would you wait for the next J!Research version (which I think will be still a beta)?

**Comment by maladd** [comment]
Please send me the patch to try.

Sorry if terse, sent from my iPhone

On Jul 14, 2015, at 9:43 AM, Luis Galárraga <notifications@github.com<mailto:notifications@github.com>> wrote:

I have found a better solution. I added an option that allows to associate the URL to either (a) the URL field in the form or (b) an attachment with a particular tag. In this way, @maladdhttps://github.com/maladd can still keep the URLs stored in the traditional url field. Do you want me to send you a patch for this or would you wait for the next J!Research version (which I think will be still a beta)

—
Reply to this email directly or view it on GitHubhttps://github.com/carcam/jresearch/issues/3#issuecomment-121241175.

The information in this e-mail is intended only for the person to whom it is
addressed. If you believe this e-mail was sent to you in error and the e-mail
contains patient information, please contact the Partners Compliance HelpLine at
http://www.partners.org/complianceline . If the e-mail was sent to you in error
but does not contain patient information, please contact the sender and properly
dispose of the e-mail.

**Comment by lgalarra** [comment]
By the way, I have not yet sent you the patch because I am doing some careful testing of the component. I have changed many things in the meantime and want to be sure I will not break your site.

**Comment by lgalarra** [comment]
Hi,

J!Research 3.0 beta 3 is out. If you want to upgrade your current installation without losing your data, download the installation package available at http://joomlaresearch.com/en/downloads.html and decompress it. Once decompressed, you will see a folder packages/ containing the individual extensions that make J!Research. Install the main component and the following plugins: plg_jresearch_search.zip, plg_jresearch_automatic_bibliography_generation.zip, plg_jresearch_automatic_citation.zip. Make sure you have a backup of your website in case something goes wrong (It worked in my personal website). Let us know the outcome. Bug reports are welcome. We want to have a stable version before the end of the summer.

Best,
Luis

**Comment by maladd** [comment]
Thanks!

Sorry if terse, sent from my iPhone

On Aug 15, 2015, at 6:20 PM, Luis Galárraga <notifications@github.com<mailto:notifications@github.com>> wrote:

Hi,

J!Research 3.0 beta 3 is out. If you want to upgrade your current installation without losing your data, download the installation package available at http://joomlaresearch.com/en/downloads.html and decompress it. Once decompressed, you will see a folder packages/ containing the individual extensions that make J!Research. Install the main component and the following plugins: plg_jresearch_search.zip, plg_jresearch_automatic_bibliography_generation.zip, plg_jresearch_automatic_citation.zip. Make sure you have a backup of your website in case something goes wrong (It worked in my personal website). Let us know the outcome. Bug reports are welcome. We want to have a stable version before the end of the summer.

Best,
Luis

—
Reply to this email directly or view it on GitHubhttps://github.com/carcam/jresearch/issues/3#issuecomment-131456553.

The information in this e-mail is intended only for the person to whom it is
addressed. If you believe this e-mail was sent to you in error and the e-mail
contains patient information, please contact the Partners Compliance HelpLine at
http://www.partners.org/complianceline . If the e-mail was sent to you in error
but does not contain patient information, please contact the sender and properly
dispose of the e-mail.
