### ISSUE TITLE
Link to internal authors in publications missing

### ISSUE THREAD

**Issue by maladd** [carcam/jresearch#4]
Just noticed there are no links on internal author names connecting to their member pages. the jresearch_publication_internal_author table contains entries, so I know they are being picked up on some level.

Still using JResearch Beta 2 & Joomla 3.4.1 Stable

**Comment by carcam** [comment]
Is this an upgrade from previous JResearch or a clean install?

**Comment by maladd** [comment]
I exported my publications out of Jresearch 1.2.2 and imported the bibtex file.

**Comment by carcam** [comment]
Can you please edit one of your internal authors and save it and check if that fixes the issue for that author? That will help debugging the issue.

**Comment by maladd** [comment]
This is what I see in the back end. The number corresponds to jresearch_member.id

![image](https://cloud.githubusercontent.com/assets/2983521/8135691/2a98d1ee-1107-11e5-8f19-e1fa2234f31d.png)

**Comment by carcam** [comment]
Can you please go to the Staff area and open for editing any of the authors on this publication and save it? After that please check if that fixes the issue for that specific author.

**Comment by maladd** [comment]
Editing the staff entry doesn't fix anything. If I replace a name the authors field, it displays lastname, firstname. Once I save the entry, the name reverts back to the jresearch_members.id entry.

**Comment by maladd** [comment]
I missed one important detail. If I type my internal author's name into the Authors field (it auto completes) and replace the existing entry, the name is then hyperlinked.

**Comment by carcam** [comment]
So the probelm is only with imported authors. Thank you very much for this detail.

**Comment by maladd** [comment]
Any success is fixing the issue? thanks!

**Comment by carcam** [comment]
Hi @maladd, we have not discussed this yet. We are trying to clean our inbox to work on jReasearch and provide a new Beta version as soons as possible.

Best!

**Comment by lgalarra** [comment]
Hi, I could reproduce this problem. It seems a problem in the export routine. I will keep you posted.

**Comment by lgalarra** [comment]
I also solved this bug. @maladd : I will send you a patch containing 2 bug fixes.
