### ISSUE TITLE
Staff list not showing a clear distinction between names and next author

### ISSUE THREAD

**Issue by carcam** [carcam/jresearch#7]
listing of the Authors. More in detail here is what authors look like in the control panel :

A Artale; D Bresolin; A Montanari; 

And so appears to the public site :

Artale, A., Bresolin, D., Montanari,

You can see the comma makes no distinction between couples of name and surname, a bit confusing.

**Comment by lgalarra** [comment]
The APA citation style unfortunately requires this forrmat, so I am closing this issue. In contrast, I found (and corrected) a bug in the author's format of the Chicago citation style implementation.
